name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn --prod
      - run: yarn build:static

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./out s3://veetour-poc --delete --acl public-read